# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYqAWwcZ2ujNxFbXzjeUS1_5kQY7Un1U
"""

pip install numpy
import numpy as np
pip install pandas
import pandas as pd
pip install matplotlib
import matplotlib.pyplot as plt
pip install sklearn
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier


dataset = pd.read_csv('diabetes.csv')



train_data=dataset.drop(columns=["Outcome","BloodPressure",'SkinThickness','DiabetesPedigreeFunction','Glucose'])
output_data=dataset['Outcome']



# Select algorithm
model = DecisionTreeClassifier()

# Fit model to the data
model.fit(train_data, output_data)


import pickle
pickle.dump(model, open('model.pkl','wb'))

model = pickle.load(open('model.pkl','rb'))

